### ISSUE TITLE
Bug in ServerMethods class 

### ISSUE THREAD

**Issue by vitalinoazevedo** [aenniw/jrobotremoteserver#24]
In method run_keyword(String, Object[]) line 121:

The split method of String class don't always return an array with length = 2 every time that the condition <arg.toString().contains("=")> resolves to true.

For example, the String "Foo==" will give an array with length = 1 using split method, resulting in a ArrayIndexOutOfBoundsException exception.

Extra note: In my case, the problem happen with a String in base64 that normally has '='s in the end.

Please fix this bug.
Thank you,
Vitalino Azevedo

**Comment by aenniw** [comment]
Hi #25 should resolve your issues... Could you look on it and confirm if this fix works for you?
Thanks

**Comment by vitalinoazevedo** [comment]
Hi there,
Yes, this solution should fix our issues.
Thanks for being so fast!

Cheers,
Vitalino Azevedo

2017-09-25 23:17 GMT+01:00 Martin Mihálek <notifications@github.com>:

**Comment by aenniw** [comment]
3.6-SNAPSHOT updated to contains fix.

**Comment by vitalinoazevedo** [comment]
When will 3.6-SNAPSHOT show up in maven central repository?

There seems to be only 3.5 at the moment.
Thanks,
Vitalino Azevedo

**Comment by aenniw** [comment]
You need to enable SNAPSHOTS in your  ~/.m2/settings.xml to use them ...
If you cannot do that or are restricted by some policies I can release that fix as 3.5.1 ...

**Comment by vitalinoazevedo** [comment]
Martin,

Ok it works now. Thanks again.

Best Regards,
Vitalino Azevedo

2017-10-11 17:27 GMT+01:00 Martin Mihálek <notifications@github.com>:
