### ISSUE TITLE
Clarification in RemoteLibrary.java interface

### ISSUE THREAD

**Issue by vitalinoazevedo** [aenniw/jrobotremoteserver#26]
Hi again,

In this Interface:
https://github.com/aenniw/jrobotremoteserver/blob/c21af42893d8243ca69d970906313fece618a688/jrobot-remote-server/src/main/java/org/robotframework/remoteserver/library/RemoteLibrary.java#L73

When this method: close() is called? We really need it?
Thanks,
Vitalino

**Comment by aenniw** [comment]
It is mapped to remote keyword "libraryCleanup", and its purpose was to expose cleanup method for libraries if needed. Otherwise it does not have any other purpose.
